### ISSUE TITLE
Docker Build failed 

### ISSUE THREAD

**Issue by CodeWithEmad** [murat-polat/tutor-authn#1]
Hi
I just followed the steps mentioned in README and in the `tutor images build authn` step, it fails. 

Step 15/23 : RUN npm install && npm run build
`
Error parsing bundle asset "/openedx/authn/dist/runtime.10d7d7146966c611c9f6.js": no such file
Error parsing bundle asset "/openedx/authn/dist/vendors~app.6e5c9845eba4648bf6b7.js": no such file
`

**Comment by murat-polat** [comment]
@CodeWithEmad Hi, and thanks for your feedback.
I just saw your comment, sorry about that.  I tried to fix and update it, and looks like its working now. But at the begining little bit slow I think. You can test it here **https://authn.baretest.xyz/register** you can test it, this is my test server will be up approx. a week. 
Thanks,
Murat

**Comment by murat-polat** [comment]
Docker build  fixed, **Register** is working properly, but **Sign In** has  some issue. Thanks.
